### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by vineethsai** [brianchesley/Lyrics#1]
with open('rush_songs.txt', 'rb') as f:
IOError: [Errno 2] No such file or directory: 'rush_songs.txt'

**Comment by vineethsai** [comment]
with open('rush_songs.pickle', 'rb') as f:
IOError: [Errno 2] No such file or directory: 'rush_songs.pickle'

Even for pickle

**Comment by VikasNS** [comment]
vineethsai , did you solve it?

**Comment by brianchesley** [comment]
The library has been overhauled, and you will no longer get this error.
